technorati_api_key: xxx
daylife_access_key: xxx
daylife_secret: xxx
twitter_consumer: xxx
twitter_secret: xxx
sunlightlabs_key: xxx
opensecrets_api_key: xxx
maplight: xxx
wiki_pass: xxx
wiki_key: xxx
wiki_callback_key: xxx
app_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
oc_session_secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
civicrm: xxx