defaults: &defaults
  current_opensecrets_cycle: '2010'
  default_search_page_size: 10
  default_congress: 112
  default_count_time: <%= 7.days %>
  default_search_page_size: 10
  available_congresses:
    - 112
    - 111
    - 110
    - 109

  scraper_useragent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.1) Gecko/20060111 Firefox/1.5.0.1
  
  mini_mailer_from: alert@dev.opencongress.org
  
  data_path: /data
  govtrack_data_path: /data/govtrack
  govtrack_billtext_path: /data/govtrack/bills.text
  govtrack_billtext_diff_path: /data/govtrack/bills.text.cmp
  oc_billtext_path: /data/opencongress/bills.text
  committee_reports_path: /data/committee_reports
  
  base_url: http://www.opencongress.org/
  api_host: api.opencongress.org
  api_base_url: http://api.opencongress.org/

  wiki_host: www.opencongress.org
  wiki_base_url: http://www.opencongress.org/wiki

  ban_file: /u/apps/opencongress/shared/files/banned_users.txt
  
development:
  <<: *defaults

  govtrack_data_path: /Users/aross/pcf-work/govtrack
  govtrack_billtext_path: /Users/aross/pcf-work/govtrack/bills.text
  govtrack_billtext_diff_path: /Users/aross/pcf-work/govtrack/bills.text.cmp
  oc_billtext_path: /Users/aross/pcf-work/oc_billtext
  committee_reports_path: /Users/aross/pcf-work/committee_reports
  
  group_images_path: /Users/aross/pcf-work/gitbranches/opencongress/public/system/group_images

  base_url: http://localhost:3000
  api_host: api.127localhost.com:3000
  api_base_url: http://api.127localhost.com:3000/

drm:
  <<: *defaults
  base_url: http://drm.dev.opencongress.org
  wiki_base_url: http://wiki-dev.opencongress.org/wiki 
  
test:
  <<: *defaults

staging:
  <<: *defaults
  
  base_url: http://dev.opencongress.org/
    
production:
  <<: *defaults
  
