
development:
  app_id: xxx
  secret: xxx
  api_key: xxx
  callback_url: xxx


staging:
  app_id: xxx
  secret: xxx
  api_key: xxx
  callback_url: xxx

oc_wiki:
  adapter: mysql
  database: ocwiki
  username: 
  password: 
  host: localhost

